version: "3.5"
services:

  opendldap:
    container_name: iris_ldap
    image: bitnami/openldap
    ports:
      - '1389:1389'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
    volumes:
      - ./ldifs:/ldifs
      - ./schemas:/schemas

# ldapsearch -H ldap://127.0.0.1:1389 -b "dc=example,dc=org" -D "cn=admin,dc=example,dc=org" -w adminpassword
# ldapsearch -H ldap://127.0.0.1:1389 -b "dc=example,dc=org" -D "cn=admin,dc=example,dc=org" -w adminpassword +
