openapi: 3.1.0
info:
  title: Specification of the API that receives data from the iris-httpsend-module
  version: 0.1.0
paths:
  /case:
    post:
      summary: Signals the creation of a new case
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - case_id
              properties:
                case_id:
                  type: integer
                  description: Identifier of the case
      responses:
        "200":
          description: Everything went fine
    delete:
      summary: Signals the deletion of a case
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: integer
              description: Identifier of the case
      responses:
        "200":
          description: Everything went fine
