openapi: 3.1.0
info:
  title: Specification of the API that receives data from the iris-httpsend-module
  version: 0.1.0
paths:
  /case:
    post:
      summary: Signals creation of a new case
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/case"
      responses:
        "200":
          description: Everything went fine
    put:
      summary: Signals update of a case
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/case"
      responses:
        "200":
          description: Everything went fine
    delete:
      summary: Signals deletion of a case
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: integer
              description: Identifier of the case
      responses:
        "200":
          description: Everything went fine
  /asset:
    post:
      summary: Signals creation of a new asset
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/asset"
      responses:
        "200":
          description: Everything went fine
    put:
      summary: Signals update of an asset
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/asset"
      responses:
        "200":
          description: Everything went fine
    delete:
      summary: Signals deletion of an asset
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: integer
              description: Identifier of the asset
      responses:
        "200":
          description: Everything went fine
  /note:
    post:
      summary: Signals creation of a new note
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/note"
      responses:
        "200":
          description: Everything went fine
    put:
      summary: Signals update of an note
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/note"
      responses:
        "200":
          description: Everything went fine
    delete:
      summary: Signals deletion of an note
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: integer
              description: Identifier of the note
      responses:
        "200":
          description: Everything went fine
  /ioc:
    post:
      summary: Signals creation of a new IOC
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ioc"
      responses:
        "200":
          description: Everything went fine
    put:
      summary: Signals update of an IOC
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ioc"
      responses:
        "200":
          description: Everything went fine
    delete:
      summary: Signals deletion of an IOC
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: integer
              description: Identifier of the IOC
      responses:
        "200":
          description: Everything went fine
  /event:
    post:
      summary: Signals creation of a new event
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/event"
      responses:
        "200":
          description: Everything went fine
    put:
      summary: Signals update of an event
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/event"
      responses:
        "200":
          description: Everything went fine
    delete:
      summary: Signals deletion of an event
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: integer
              description: Identifier of the event
      responses:
        "200":
          description: Everything went fine
  /evidence:
    post:
      summary: Signals creation of a new evidence
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/evidence"
      responses:
        "200":
          description: Everything went fine
    put:
      summary: Signals update of an evidence
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/evidence"
      responses:
        "200":
          description: Everything went fine
    delete:
      summary: Signals deletion of an evidence
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: integer
              description: Identifier of the evidence
      responses:
        "200":
          description: Everything went fine
  /task:
    post:
      summary: Signals creation of a new task
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/task"
      responses:
        "200":
          description: Everything went fine
    put:
      summary: Signals update of a task
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/task"
      responses:
        "200":
          description: Everything went fine
    delete:
      summary: Signals deletion of a task
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: integer
              description: Identifier of the task
      responses:
        "200":
          description: Everything went fine
components:
  schemas:
    case:
      type: object
      required:
        - case_id
        - user_id
        - case_name
        - case_description
        - case_customer
        - case_soc_id
        - open_date
      properties:
        case_id:
          type: integer
          description: Identifier of the case
        user_id:
          type: number
        case_name:
          type: string
        case_description:
          type: string
        classification_id:
          type: integer
          nullable: true
        case_customer:
          type: number
        case_soc_id:
          type: string
        open_date:
          type: string
        close_date:
          type: string
          nullable: true
      x-examples:
        case_id: 97
        case_name: "#97 - my_case_api"
        case_description: "a description"
        classification_id: 8
        case_customer: 1
        case_soc_id: "156516"
        user_id: 4
        open_date: "2021-10-21"
        close_date: null
    asset:
      type: object
      required:
        - asset_id
        - user_id
        - case_id
        - asset_name
        - asset_description
        - analysis_status_id
        - asset_domain
        - asset_info
        - asset_tags
        - asset_type_id
        - asset_compromise_status_id
        - date_update
        - date_added
        - asset_ip
      properties:
        asset_id:
          type: integer
          description: Identifier of the asset
        user_id:
          type: number
        case_id:
          type: integer
          description: Identifier of the case
        asset_name:
          type: string
        asset_description:
          type: string
        analysis_status_id:
          type: number
        asset_domain:
          type: string
        asset_info:
          type: string
        asset_tags:
          type: string
        asset_type_id:
          type: number
        asset_compromise_status_id:
          type: integer
        date_update:
          type: string
        date_added:
          type: string
        asset_ip:
          type: string
      x-examples:
        case_id: 2
        asset_id: 2208
        analysis_status_id: 2
        asset_domain: "My domain"
        asset_info: "Additional info"
        asset_description: "Asset description"
        asset_tags: "Asset,tags"
        asset_type_id: 1
        asset_compromise_status_id: 0
        date_update: "2022-01-21T17:42:37.286203"
        user_id: 1
        asset_name: "Asset 1"
        date_added: "2022-01-21T17:42:37.286192"
        asset_ip: My IP
    note:
      type: object
      required:
        - note_id
        - note_content
        - note_title
      properties:
        note_id:
          type: number
        note_content:
          type: string
        note_title:
          type: string
      x-examples:
        note_id: 2362
        note_title: "note title"
        note_content: "some content"
    ioc:
      type: object
      required:
        - ioc_id
        - user_id
        - ioc_description
        - ioc_value
        - ioc_tags
        - ioc_type_id
        - ioc_tlp_id
      properties:
        ioc_id:
          type: number
        user_id:
          type: number
        ioc_description:
          type: string
        ioc_value:
          type: string
        ioc_tags:
          type: string
        ioc_type_id:
          type: number
        ioc_tlp_id:
          type: number
      x-examples:
        ioc_id: 1
        user_id: 1
        ioc_description: "Description"
        ioc_value: "hello"
        ioc_tags: ""
        ioc_type_id: 4
        ioc_tlp_id: 2
    event:
      type: object
      required:
        - event_id
        - user_id
        - case_id
        - event_title
        - event_date
        - event_date_wtz
        - event_tz
        - event_content
        - event_tags
        - event_raw
        - event_color
        - event_source
        - event_in_summary
        - event_in_graph
        - event_added
      properties:
        event_id:
          type: number
        user_id:
          type: number
        case_id:
          type: number
        event_title:
          type: string
        event_date:
          type: string
        event_date_wtz:
          type: string
        event_tz:
          type: string
        event_content:
          type: string
        event_tags:
          type: string
        event_raw:
          type: string
        event_color:
          type: string
        event_source:
          type: string
        event_in_summary:
          type: boolean
        event_in_graph:
          type: boolean
        event_added:
          type: string
      x-examples:
        event_id: 14985
        user_id: 1
        case_id: 2
        event_title: "Tests"
        event_date: "2021-12-12T05:45:46.000000"
        event_date_wtz: "2021-12-12T05:45:46.000000"
        event_tz: "+00:00"
        event_content: ""
        event_tags: ""
        event_raw: ""
        event_color: "#6861CE99"
        event_source: ""
        event_in_summary: true
        event_in_graph: true
        event_added: "2022-01-21T19:17:16.154055"
    evidence:
      type: object
      required:
        - id
        - filename
        - file_description
        - file_hash
        - file_size
        - date_added
      properties:
        id:
          type: number
        filename:
          type: string
        file_description:
          type: string
        file_hash:
          type: string
        file_size:
          type: number
        date_added:
          type: string
      x-examples:
        id: 2
        filename: "demo.csv"
        file_description: "some description"
        file_hash: "d2e891600921f39bc7fd6e234c574005"
        file_size: 231
        date_added: "2023-05-26T08:43:44.177907"
    task:
      type: object
      required:
        - id
        - task_case_id
        - task_title
        - task_description
        - task_status_id
        - task_tags
        - task_userid_open
        - task_userid_update
        - task_open_date
        - task_last_update
      properties:
        id:
          type: number
        task_case_id:
          type: number
        task_title:
          type: string
        task_description:
          type: string
        task_status_id:
          type: number
        task_tags:
          type: string
        task_userid_open:
          type: number
        task_userid_update:
          type: number
        task_open_date:
          type: string
        task_last_update:
          type: string
      x-examples:
        id: 26
        task_case_id: 2
        task_title: "Super task"
        task_description: "Task"
        task_status_id: 15
        task_tags: "tag1,tag2"
        task_userid_open: 1
        task_userid_update: 1
        task_open_date: '2022-01-21T19:31:15.964472'
        task_last_update: '2022-01-21T19:31:15.964472'
