openapi: 3.1.0
info:
  title: Specification of the API that receives data from the iris-httpsend-module
  version: 0.1.0
paths:
  /case:
    post:
      summary: Signals creation of a new case
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/case"
      responses:
        "200":
          description: Everything went fine
    delete:
      summary: Signals deletion of a case
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: integer
              description: Identifier of the case
      responses:
        "200":
          description: Everything went fine
  /asset:
    post:
      summary: Signals creation of a new asset
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/asset"
      responses:
        "200":
          description: Everything went fine
    put:
      summary: Signals update of an asset
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/asset"
      responses:
        "200":
          description: Everything went fine
    delete:
      summary: Signals deletion of an asset
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: integer
              description: Identifier of the case
      responses:
        "200":
          description: Everything went fine
components:
  schemas:
    case:
      type: object
      required:
        - case_id
        - case_name
        - case_description
        - case_customer
        - case_soc_id
        - user_id
        - open_date
      properties:
        case_id:
          type: integer
          description: Identifier of the case
        case_name:
          type: string
        case_description:
          type: string
        classification_id:
          type: integer
          nullable: true
        case_customer:
          type: number
        case_soc_id:
          type: string
        user_id:
          type: number
        open_date:
          type: string
        close_date:
          type: string
          nullable: true
      x-examples:
        case_id: 97
        case_name: ""#97 - my_case_api"
        case_description: "a description"
        classification_id: 8
        case_customer: 1
        case_soc_id: "156516"
        user_id: 4
        open_date: "2021-10-21"
        close_date: null
    asset:
      type: object
      required:
        - case_id
        - asset_id
      properties:
        case_id:
          type: integer
          description: Identifier of the case
        asset_id:
          type: integer
          description: Identifier of the asset