openapi: 3.1.0
info:
  title: Specification of the API that receives data from the iris-httpsend-module
  version: 0.1.0
paths:
  /case:
    post:
      summary: Signals creation of a new case
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - case_id
              properties:
                case_id:
                  type: integer
                  description: Identifier of the case
      responses:
        "200":
          description: Everything went fine
  /case/{identifier}:
    delete:
      summary: Signals deletion of a case
      description:
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: integer
          description: Identifier of the case
      responses:
        "200":
          description: Everything went fine
  /asset:
    post:
      summary: Signals creation of a new asset
      description:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - case_id
                - asset_id
              properties:
                case_id:
                  type: integer
                  description: Identifier of the case
                asset_id:
                  type: integer
                  description: Identifier of the asset
      responses:
        "200":
          description: Everything went fine
  /asset/{identifier}:
    delete:
      summary: Signals deletion of an asset
      description:
      parameters:
        - name: identifier
          in: path
          required: true
          schema:
            type: integer
          description: Identifier of the case
      responses:
        "200":
          description: Everything went fine
