name: Continuous Integration
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      IRIS_VERSION: v2.0.0-beta-1
      HTTPSEND_VERSION: 0.1.0
    steps:
      - name: Check out Iris ${{ env.IRIS_VERSION }}
        uses: actions/checkout@v3
        with:
          repository: dfir-iris/iris-web
          ref: ${{ env.IRIS_VERSION }}
          path: iris-web
      - name: Building dockers
        working-directory: iris-web
        run: |
          docker build --tag iris-web_db docker/db
          docker build --build-arg NGINX_CONF_GID=1234 --build-arg NGINX_CONF_FILE=nginx.conf --tag iriswebapp_nginx docker/nginx
          docker build --file docker/webApp/Dockerfile --tag iriswebapp_app .
      - name: Check out iris-httpsend-module ${{ env.HTTPSEND_VERSION }}
        uses: actions/checkout@v3
        with:
          path: iris-httpsend-module
      - name: Archive dockers
        working-directory: iris-httpsend-module
        run: |
          mkdir results
          docker save iris-web_db iriswebapp_nginx iriswebapp_app | gzip > results/iris-httpsend-${{ env.HTTPSEND_VERSION }}.dockers.tar.gz
      - name: Save dockers as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dockers
          path: iris-httpsend-module/results/iris-httpsend-${{ env.HTTPSEND_VERSION }}.dockers.tar
          if-no-files-found: error
          retention-days: 2
