name: Continuous Integration
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      IRIS_VERSION: v2.0.0-beta-1
    steps:
      - name: Check out Iris ${{ env.IRIS_VERSION }}
        uses: actions/checkout@v3
        with:
          repository: dfir-iris/iris-web
          ref: ${{ env.IRIS_VERSION }}
          path: iris-web
      - name: Building dockers
        working-directory: iris-web
        run: |
          docker build --tag iris-web_db docker/db
